services:
  api:
    build:
      context: ../..
      dockerfile: code/deployment/api/Dockerfile
    container_name: diabetes-api
    ports:
      - "8000:8000"
    restart: unless-stopped

  app:
    build:
      context: ./app
    container_name: diabetes-app
    ports:
      - "8501:8501"
    environment:
      API_URL: http://api:8000
    depends_on:
      - api
    restart: unless-stopped